name: Deploy website on release
on:
  release:
    types: [published]
jobs:
  pre-web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: init job info
        run: echo "The job was triggered by a ${{ github.event_name }} event on branch ${{ github.ref }}"

  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 📂 Get latest code
      uses: actions/checkout@v2
    - name: 📤 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.epimap.fr
        local-dir: ./src/
        username: epima1723318
        password: ${{ secrets.ftp_password }}